server:
  port: 8080
  servlet:
    context-path: /combate

spring:
  application:
    name: fortivus-v2
  
  profiles:
    active: local

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5444/fortivus
    username: postgres
    password: fortivus_local_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: operacional
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true
    validate-on-migrate: false
    schemas: operacional
    table: migrations

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    vault:
      enabled: false 
      host: localhost
      port: 8202
      scheme: http
      authentication: TOKEN
      token: dev-token

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:9000/realms/fortivus/protocol/openid-connect/certs}


management:
  health:
    redis:
      enabled: false

# Configurações Customizadas FORTIVUS
fortivus:
  storage:
    s3:
      endpoint: http://localhost:8333 # SeaweedFS S3 API
      access-key: any
      secret-key: any
      bucket: fortivus-v2
  logs:
    path: ./logs
